[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RayFed"
authors = [{name = "The RayFed Team", email = "rayfed-dev@googlegroups.com"}]
dynamic = ["version", "description"]
