name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    timeout-minutes: 10 # Lint should be done in 10 minutes.
    runs-on: ubuntu-latest
    container: docker.io/library/ubuntu:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install bazel
      run:  |
            apt-get update
            apt-get install -yq wget gcc g++ python3.9 zlib1g-dev zip libuv1.dev
            apt-get install -yq pip

    - name: Install dependencies
      run:  |
            python3 -m pip install virtualenv
            python3 -m virtualenv -p python3 py3
            . py3/bin/activate
            which python
            pip install ray==2.0.0
            pip install black==23.1

    - name: Lint
      run: |
           . py3/bin/activate
           black  -S --check --diff . --exclude='fed/grpc|py3'
