name: test on ray1.13.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-unit-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: docker.io/library/ubuntu:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install bazel
      run:  |
            apt-get update
            apt-get install -yq wget gcc g++ python3.9 zlib1g-dev zip libuv1.dev
            apt-get install -yq pip

    - name: Install dependencies
      run:  |
            python3 -m pip install virtualenv
            python3 -m virtualenv -p python3 py3
            . py3/bin/activate
            which python
            pip install pytest torch cloudpickle cryptography
            pip install ray==1.13.0

    - name: Build and test
      run: |
           . py3/bin/activate
           pip install -e . -v
           sh test.sh
