name: test on many rays

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-unit-tests-on-many-rays:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ray_version: [2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.5.1, 2.6.3, 2.7.1, 2.8.1]

    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: docker.io/library/ubuntu:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install basic dependencies
      run:  |
            apt-get update
            apt-get install -yq wget gcc g++ python3.9 zlib1g-dev zip libuv1.dev
            apt-get install -yq pip

    - name: Install python dependencies
      run:  |
            python3 -m pip install virtualenv
            python3 -m virtualenv -p python3 py3
            . py3/bin/activate
            which python
            pip install pytest torch cloudpickle cryptography
            # six is required in ray-2.1.0
            # grpc is required since ray-2.8.0
            pip install "protobuf<4.0" six grpcio
            pip install ray==${{ matrix.ray_version }}

    - name: Build and test
      run: |
           . py3/bin/activate
           pip install -e . -v
           sh test.sh
