name: test for protobuf4

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-unit-tests-on-for-protobuf4:
    strategy:
        protobuf_ver: [3.19, 3.20]

    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: docker.io/library/ubuntu:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install basic dependencies
      run:  |
            apt-get update
            apt-get install -yq wget gcc g++ python3.9 zlib1g-dev zip libuv1.dev
            apt-get install -yq pip

    - name: Install python dependencies
      run:  |
            python3 -m pip install virtualenv
            python3 -m virtualenv -p python3 py3
            . py3/bin/activate
            which python
            pip install pytest torch cloudpickle cryptography
            pip install protobuf==${{ protobuf_ver }}
            pip install ray==2.4.0

    - name: Build and test
      run: |
           . py3/bin/activate
           pip install -e . -v
           sh test.sh