name: test on many rays

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-unit-tests-on-many-rays:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ray_version: [2.31.0, 2.32.0, 2.33.0, 2.34.0, 2.35.0]

    timeout-minutes: 60
    runs-on: ubuntu-22.04
    container: docker.io/library/ubuntu:22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install basic dependencies
      run:  |
            apt-get update
            apt-get install -yq wget gcc g++ python3.10 zlib1g-dev zip libuv1.dev
            apt-get install -yq pip

    - name: Install python dependencies
      run:  |
            python3 -m pip install virtualenv
            python3 -m virtualenv -p python3 py3
            . py3/bin/activate
            which python
            # Revert setuptools for compatibility with ray dashboard.
            pip install setuptools==69.5.1
            pip install pytest
            pip install -r dev-requirements.txt
            pip install ray==${{ matrix.ray_version }}
            grep -ivE "ray" requirements.txt > temp_requirement.txt
            pip install -r temp_requirement.txt

    - name: Build and test
      run: |
           . py3/bin/activate
           pip install -e . -v
           sh test.sh
